# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "208f20239c84a073a18ea42f78e29d7b"
application_url = "https://example.com"
embedded = true
name = "SOPHÉA Website"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "unauthenticated_read_product_listings,unauthenticated_read_product_inventory,unauthenticated_read_product_tags,unauthenticated_read_customers,unauthenticated_write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ ]

[webhooks]
api_version = "2026-07"
